---
title: "transformagov_painel"
output: html_document
---



```{r setup, include=FALSE}
options(scipen=999)
options(digits=2)
# options (LC_NUMERIC="pt_BR.UTF-8")
```




```{r libraries,  message=FALSE}
library(flexdashboard)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(shiny)
library(shinyWidgets)
library(lubridate)
library(tidyverse)
library(janitor)
library(googledrive)
library(gargle)

```

```{r}
# profvis({  
# profvis::profvis(expr = rmarkdown::run("flexdashboard.Rmd"), prof_output = "flexdashboard.html")
# https://community.rstudio.com/t/faster-flexdashboard-loading/28681/2
```



```{r negar %in%}
# https://www.r-bloggers.com/the-notin-operator/
'%!in%' <- Negate('%in%')
```

```{r função "dados" importar e renomear variaveis}
# funcao para importar dados e renomear variaveis
dados = function(tg, depara){
  # carregar planilha com dados do Tesouro Gerencial (tg)
  df <- read_xlsx(tg)
  # carregar planilha com o de_para dos nomes dos atributos do Tesouro Gerencial para nomes mais amigáveis para as variáveis. Por exemplo, de(Unidade Orçamentária Código) para(uo_cod)
  tg2r <- read_xlsx(depara)
  # renomear as colunas da df fazendo o de_para
  colnames(df)<-tg2r$r_name
  return(df)
}
```

```{r função "tabela" formatar numeros incluir totalizador}
# comentar funcao e parametro para totalizar colunas e linhas
# ajustar formatacao de acordo com a opcao de totalizar
# criar forma melhor para selecionar apenas colunas numericas para formatacao de valor
# coluna = "Total" para totalizar columnwise
tabela = function (df,coluna = NULL) {
      datatable((df)%>%
  # "row" para o total aparecer na linha, ou seja, totalizar os valores de uma coluna
  adorn_totals("row") ,
      filter = 'top',          
      extensions = 'Buttons',
      options = list( 
                  # order = list (df[(length(df))], 'desc'),
                  dom = "Blfrtip",
                  buttons = 
                    list("copy", list(
                      extend = "collection",
                      buttons = c("csv", "excel", "pdf"),
                      text = "Download" ) ),
                  lengthMenu = list( c(-1, 5, 10,20),
                                     c( "tudo",5, 10, 20)),
                  pageLength = -1 )
      )%>%
  formatRound(
  # formatar apenas as colunas numericas.
  # sapply para identificar as colunas numericas e combinar com o parametro COLUNA
    # ((ncol(df %>% select_if(is.character))+1):(ncol(df )+1)),
    # http://datamining.togaware.com/survivor/Remove_Non_Numeric.html
    (c(colnames(df[,sapply(df, is.numeric)]), coluna)),
  digits = 2,
  interval = 3,
  mark = ",",
  dec.mark = getOption("OutDec")
)
}
# mesma lógica da função "tabela", mas com o objetivo de apresentar os números no formato R$
tabela_reais = function (df,coluna = NULL) {
      datatable((df)%>%
  # "row" para o total aparecer na linha, ou seja, totalizar os valores de uma coluna
  adorn_totals("row") ,
      filter = 'top', 
      rownames = FALSE,
      extensions = 'Buttons',
      options = list( 
                  # order = list (df[(length(df))], 'desc'),
                  dom = "Blfrtip",
                  buttons = 
                    list("copy", list(
                      extend = "collection",
                      buttons = c("csv", "excel", "pdf"),
                      text = "Download" ) ),
                  lengthMenu = list( c(-1, 5, 10,20),
                                     c( "tudo",5, 10, 20)),
                  pageLength = -1 )
      )%>%
  formatRound(
  # formatar apenas as colunas numericas.
  # sapply para identificar as colunas numericas e combinar com o parametro COLUNA
    # ((ncol(df %>% select_if(is.character))+1):(ncol(df )+1)),
    # http://datamining.togaware.com/survivor/Remove_Non_Numeric.html
    (c(colnames(df[,sapply(df, is.numeric)]), coluna)),
  digits = 2,
  interval = 3,
  mark = ".",
  dec.mark = ","
) 
}
```



```{r função "reais" para embelezar numeros}
# embelezar o número do value box
reais <- function(numero){
  paste0("R$ ",round(numero/1000,digits = 1), " K")
}
```



```{r}
norte_base <- read_excel("norte_base.xlsx")
sul_base <- read_excel("sul_base.xlsx")
nordeste_base <- read_excel("nordeste_base.xlsx")
sudeste_base <- read_excel("sudeste_base.xlsx")
centro_oeste_base <- read_excel("centro_oeste_base.xlsx")
```


```{r}
uniao <- rbind(nordeste_base,sul_base,nordeste_base,sudeste_base,centro_oeste_base)

```

```{r}
datatable(uniao)
```

